### ISSUE TITLE
Gii experiment structure in the cafer package

### ISSUE THREAD

**Issue by luis-calvo-varela** [robotsthatdream/cafer#14]
How should we add our experiment to the cafer package? 

As another package at the same level of the cafer_core package? As a folder inside the cafer_core package?

Thanks

**Comment by doncieux** [comment]
Any adaptation to the cafer_core (notably the java version of the component) should be in the cafer_core folder. Any other experiment specific aspect should be in in folder at the same level as sferes and cafer_core.
