### ISSUE TITLE
Problem building the cafer data_manager branch

### ISSUE THREAD

**Issue by luis-calvo-varela** [robotsthatdream/cafer#15]
manager_test.msg is missing

**Comment by cmaestre** [comment]
Which file (.hpp/.cpp I guess) is making a reference to the message? CMakeLists.txt makes only this reference to a message:

add_message_files(
  FILES
  Management.msg
)

**Comment by luis-calvo-varela** [comment]
CMakeLists.txt under the cafer data_manager branch adds a reference to a manager_test.msg that is not present in the msg folder. It is used by the data_manager_example.cpp.

**Comment by LeniLeGoff** [comment]
Yeah sorry, I forget to add manager_test.msg.

**Comment by LeniLeGoff** [comment]
I have commited changes to CMakelist.txt and add manager_test.msg
But to install you must run this command catkin_make install -DCMAKE_INSTALL_PREFIX=/usr/local

**Comment by luis-calvo-varela** [comment]
Thank you. I will test it and see if our experiment runs well on this branch.
