### ISSUE TITLE
Problem with the service get_it and the node namespace

### ISSUE THREAD

**Issue by luis-calvo-varela** [robotsthatdream/cafer#16]
When "basic_example_launch_set_nodes.launch" is launched, the service get_id fails. The problem is the namespace "/cafer_core".

It works if the node namespace is changed to "/cafer_server".

**Comment by cmaestre** [comment]
Yes, but you are mixing the main branch and the data_manager branch, which are not being merged yet. The right name of the namespace is "/cafer_core", which has to be updated in the data_manager branch.

**Comment by luis-calvo-varela** [comment]
Yes, this time i was using the master branch to test your recently added examples.

I will keep testing them with the current master branch until the two branches are merged.

Thank you.
