### ISSUE TITLE
Merge current data_manager branch with the master branch

### ISSUE THREAD

**Issue by cmaestre** [robotsthatdream/cafer#17]
To do ASAP to avoid compatibilty problems ;-)

Several things are missing:
- to merge the files for the data management
- to update the files for the basic examples with the new abstract class instead of the current DummyClient
- to integrate the basic example and the data management examples in the same folder (/src/cafer_core/examples/management_data and /src/cafer_core/examples/basic_example)
- update the wiki with the new location of the files

**Comment by LeniLeGoff** [comment]
to update the files for the basic examples with the new abstract class instead of the current DummyClient - Done
to integrate the basic example and the data management examples in the same folder (/src/cafer_core/examples/management_data and /src/cafer_core/examples/basic_example) - Done

**Comment by cmaestre** [comment]
Léni, in the master branch there are not commits from yesterday...

**Comment by cmaestre** [comment]
The merge is done
