### ISSUE TITLE
Handling the cafer_core headers

### ISSUE THREAD

**Issue by luis-calvo-varela** [robotsthatdream/cafer#18]
Since i had to modify the cafer_core cmakelist.txt from the previous version of cafer in order to be able to import the cafer core component into my package code, and there is a header problem with the current data_manager branch, this is how i solved it (there is a cleaner way to do it, though):

1) Add to the cmakelist.txt:

catkin_package(
  **INCLUDE_DIRS src**
  **LIBRARIES cafer_core**
  CATKIN_DEPENDS roscpp std_msgs message_runtime roslib
  DEPENDS system_lib
)

**install(DIRECTORY src/${PROJECT_NAME}/**
**DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}**
**FILES_MATCHING PATTERN "*.hpp"**
**PATTERN ".svn" EXCLUDE)**

2) Import the library on external packages/same package with:

```
#include <file.hpp>
```

This way we can both compile the branch and use the cafer classes in our experiment code.

**Comment by cmaestre** [comment]
Hi! I am about to commit a new merged version with everything working ;-)

**Comment by luis-calvo-varela** [comment]
Ok, that is great. i will test our experiment with that version to see if it is still needed to do this in order to use the cafer libraries in our code.

**Comment by cmaestre** [comment]
Included in the new merge
