### ISSUE TITLE
MDB structure in the Cafer package

### ISSUE THREAD

**Issue by luis-calvo-varela** [robotsthatdream/cafer#19]
Hi, 

i have a question about the structure of our experiment.

Right now, it consists in two packages:
1) **rosmdb**: The rosjava wrapper of the experiment. 
2) **cafer_mdb**: The c++ link between cafer and rosmdb. 

My idea is to put them both in a _cafer/mdb_ folder and move them to the needed folders (following the tutorial i will add) after the cafer package is downloaded: **cafer_mdb** would end in the _cafer/src_ folder and **rosmdb** would end in a rosjava workspace.

What do you think?

**Comment by cmaestre** [comment]
My idea would be to leave it out of the /cafer_core right now, at the same level that the /sferes folder. In the future we can create something like cafer_core_cpp and cafer_core_java folders

**Comment by luis-calvo-varela** [comment]
Done ;)
