### ISSUE TITLE
Problem with the recently merged master-branch

### ISSUE THREAD

**Issue by luis-calvo-varela** [robotsthatdream/cafer#20]
The cafer_core cmakelist.txt has duplicated code and some added garbage.

Other files have duplicated code as well.

**Comment by LeniLeGoff** [comment]
I have push a last commit. Now the master branch is stable. There are no more duplicate code.
Need a check to close this issue.

**Comment by luis-calvo-varela** [comment]
Ok, i will try it right now and report the results here.

**Comment by luis-calvo-varela** [comment]
Did you push it already? Because the last commit right now is from 22 hours ago.

**Comment by LeniLeGoff** [comment]
Yes I have pushed already but the commit is from 22 hours ago.

**Comment by luis-calvo-varela** [comment]
Ok, let's check it then.

**Comment by luis-calvo-varela** [comment]
It builds and it works without problems.

We can close the issue.
