### ISSUE TITLE
MDB-Cafer related packages layout in the Dream repository

### ISSUE THREAD

**Issue by luis-calvo-varela** [robotsthatdream/cafer#28]
Hi all, 

how should the mdb-cafer related packages be arranged in the repository?

My plan is to make different projects: cafer_core_java, cafer_mdb, etc

I'm working now on the tutorials, so i will create them as soon as these are finished.

**Comment by cmaestre** [comment]
Luis,  you should do different repositories (with these names):
- ros_java : only if you need to make a bridge between ROS and Java
- cafer_java : to replicate the current functionality in CPP "cafer" repository (using the ros_java functionality) 
- cafer_mdb : the cognitive architecture (using the cafer_java functionality)

**Comment by luis-calvo-varela** [comment]
Ok, 

thanks for the answer Carlos.

**Comment by luis-calvo-varela** [comment]
Done.
